import { randomUUID } from "node:crypto";

/**
 * Entity identifiers are generated by the application before persistence.
 * Keep this as the single source of UUID generation; database migrations must
 * not add a competing UUID default unless this contract is deliberately changed.
 */
export function createEntityId(): string {
  return randomUUID();
}
